**This notebook contains all models for regression with their import function and metrics to help in interview prep.**

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Dataset :- Housing Price Predictor**

In [12]:
df = pd.read_csv('Datasets/regression.csv')
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [13]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

X = df.drop('price', axis=1)
y=df["price"]

categorical_cols = [
    'mainroad',
    'guestroom',
    'basement',
    'hotwaterheating',
    'airconditioning',
    'prefarea',
    'furnishingstatus'
]

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(drop='first'), categorical_cols)
    ],
    remainder='passthrough'
)

X_encoded = ct.fit_transform(X)

In [16]:
# Get feature names
encoded_feature_names = ct.get_feature_names_out()

# Convert to DataFrame
X_encoded = pd.DataFrame(X_encoded, columns=encoded_feature_names)

X_encoded.head()

,encoder__mainroad_yes,encoder__guestroom_yes,encoder__basement_yes,encoder__hotwaterheating_yes,encoder__airconditioning_yes,encoder__prefarea_yes,encoder__furnishingstatus_semi-furnished,encoder__furnishingstatus_unfurnished,remainder__area,remainder__bedrooms,remainder__bathrooms,remainder__stories,remainder__parking
0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,7420.0,4.0,2.0,3.0,2.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,8960.0,4.0,4.0,4.0,3.0
2,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,9960.0,3.0,2.0,2.0,2.0
3,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,7500.0,4.0,2.0,2.0,3.0
4,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,7420.0,4.0,1.0,2.0,2.0

In [ ]:
#Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_encoded['remainder__area','remainder_bathrooms','remainder_stories','remainder_parking'] = scaler.fit_transform(X_encoded[['remainder__area','remainder_bathrooms','remainder_stories','remainder_parking']])
X_encoded.head()

,encoder__mainroad_yes,encoder__guestroom_yes,encoder__basement_yes,encoder__hotwaterheating_yes,encoder__airconditioning_yes,encoder__prefarea_yes,encoder__furnishingstatus_semi-furnished,encoder__furnishingstatus_unfurnished,remainder__area,remainder__bedrooms,remainder__bathrooms,remainder__stories,remainder__parking
0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.046726,4.0,2.0,3.0,2.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.757010,4.0,4.0,4.0,3.0
2,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,2.218232,3.0,2.0,2.0,2.0
3,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.083624,4.0,2.0,2.0,3.0
4,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.046726,4.0,1.0,2.0,2.0

In [ ]:
# Data split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

**Linear Regression**

In [36]:
#Linear Regression
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [37]:
# Accuracy Metirc
predictLR = model.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test, predictLR)

0.6494754192267792

In [ ]:
# Checking price for a house with manual input
# attributes with values for checking regression
# Manual input
data = {
    'area': [9960],
    'bedrooms': [3],
    'bathrooms': [3],
    'stories': [2],
    'mainroad': ['yes'],
    'guestroom': ['no'],
    'basement': ['yes'],
    'hotwaterheating': ['no'],
    'airconditioning': ['no'],
    'parking': [2],
    'prefarea': ['yes'],
    'furnishingstatus': ['semi-furnished']
}

# Convert to DataFrame
test_df = pd.DataFrame(data)


model.predict([])